export const DEMO_SAMPLES = [
  { name: "Happy lift", mood: "Happy", key: "C", chordType: "major", octave: 4, bpm: 126, pitchLineCount: 4, progression: [["C", "major"], ["G", "major"], ["A", "minor"], ["F", "major"], ["D", "minor"], ["G", "major"], ["C", "major"]], lengths: [4, 4, 6, 2, 4, 4, 8] },
  { name: "Sad open sky", mood: "Sad", key: "D", chordType: "minor", octave: 4, bpm: 78, pitchLineCount: 4, progression: [["D", "minor"], ["A", "minor"], ["A#", "major"], ["F", "major"], ["G", "minor"], ["A", "minor"], ["D", "minor"]], lengths: [6, 4, 4, 6, 4, 2, 8] },
  { name: "Suspense pulse", mood: "Suspense", key: "E", chordType: "minor", octave: 3, bpm: 96, pitchLineCount: 5, progression: [["E", "minor"], ["F", "major"], ["E", "minor"], ["C", "major"], ["B", "dominant 7"], ["E", "minor"]], lengths: [2, 2, 4, 6, 2, 8] },
  { name: "Creepy glass", mood: "Creepy", key: "F#", chordType: "minor", octave: 4, bpm: 70, pitchLineCount: 5, progression: [["F#", "minor"], ["D", "major"], ["G", "minor"], ["C#", "dominant 7"], ["F#", "minor"]], lengths: [5, 3, 6, 2, 8] },
  { name: "Heroic brass pad", mood: "Heroic", key: "G", chordType: "major", octave: 3, bpm: 112, pitchLineCount: 5, progression: [["G", "major"], ["D", "major"], ["E", "minor"], ["C", "major"], ["A", "minor"], ["D", "dominant 7"], ["G", "major"]], lengths: [4, 4, 4, 8, 2, 2, 8] },
  { name: "Dreamy shimmer", mood: "Dreamy", key: "F", chordType: "major 7", octave: 4, bpm: 86, pitchLineCount: 5, progression: [["F", "major 7"], ["C", "major"], ["D", "minor 7"], ["A#", "major 7"], ["G", "minor"], ["C", "dominant 7"], ["F", "major 7"]], lengths: [8, 4, 6, 6, 4, 2, 8] },
  { name: "Dark cinematic rise", mood: "Dark cinematic", key: "C", chordType: "minor", octave: 3, bpm: 84, pitchLineCount: 6, progression: [["C", "minor"], ["G#", "major"], ["D#", "major"], ["A#", "major"], ["G", "dominant 7"], ["C", "minor"]], lengths: [6, 4, 4, 6, 2, 10] },
  { name: "Calm ambient drift", mood: "Calm ambient", key: "A", chordType: "major 7", octave: 3, bpm: 64, pitchLineCount: 4, progression: [["A", "major 7"], ["E", "major"], ["F#", "minor 7"], ["D", "major 7"], ["B", "minor 7"], ["E", "major"], ["A", "major 7"]], lengths: [8, 6, 8, 6, 4, 4, 10] },
  { name: "Minor descending color progression", mood: "melancholic / cinematic", key: "A", chordType: "minor", octave: 4, bpm: 80, pitchLineCount: 4, progression: [["A", "minor"], ["Custom", "major", ["A", "C", "E", "G#"]], ["A", "minor 7"], ["Custom", "major", ["A", "C", "E", "F#"]], ["F", "major 7"], ["E", "minor 7"], ["D", "minor 7"], ["G", "dominant 7"], ["C", "major 7"], ["F", "major 7"], ["Custom", "major", ["B", "D", "F", "A"]], ["E", "dominant 7"], ["A", "minor"], ["E", "dominant 7"], ["A", "minor"]], lengths: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2] },
];
